#!/bin/bash

gs="$(dirname "$0")";
data="$gs/files/";
jslibJS="$(realpath "$gs/../jslib/lib.js/")";
tmpFile="$(mktemp)";

(
	cd "$data";
	for lib in lib/*.js; do
		source="$jslibJS/$(basename "$lib")";
		if [ "$lib" -nt "$source" -o "$lib" -ot "$source" ]; then
			cp -f --preserve=timestamps "$source" "$lib";
		fi;
	done;
	$jslib/html.sh "$($jslib/requiredHTML.sh game.js)" lib/html.js;
	head -n5 index.html | tr -d '\n	';
	echo -n "<script type=\"module\">";
	(
		echo "const pageLoad = (document.readyState == \"complete\" ? Promise.resolve() : new Promise(successFn => globalThis.addEventListener(\"load\", successFn, {once: true})))";
		jspacker -i "/$(grep "<script" index.html | sed -e 's/.*src="\([^"]*\)".*/\1/')" -n | tail -n+2;
	) | terser -m  --module --compress pure_getters,passes=3 --ecma 6 | tr -d '\n';
	tail -n6 index.html | tr -d '\n	';
) > "$tmpFile";

echo -e "package gameserver\n\nconst (\n	uncompressedSize = $(stat --format "%s" "$tmpFile")\n	indexUpdated     = $(date "+%s")\n)" > "index_size.go";

zopfli --gzip --i1000 -c "$tmpFile" > index.gz;
rm -f "$tmpFile";
